stages:
  - lint
  - test

image: "harbor.drom.ru/library/drom-php:toolbox-7.4"

cache:
  paths:
    - vendor/

.lint-template: &lint-template
  stage: lint
  when: always
  before_script:
    - composer install --prefer-dist --no-progress --no-suggest

phpstan:
  <<: *lint-template
  script:
    - composer run phpstan

phpcs:
  <<: *lint-template
  script:
    - composer run phpcs

phpmd:
  <<: *lint-template
  allow_failure: true
  script:
    - composer run phpmd

ecs:
  <<: *lint-template
  script:
    - composer run ecs

phpunit:
  stage: test
  when: always
  before_script:
    - composer install --prefer-dist --no-progress --no-suggest
  script:
    - composer run phpunit
