name: Lint Code Base

on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "7.4.26"
          version: 2

      - name: Lint
        run: |
          composer run phpstan
          composer run phpcs
          composer run phpmd
          composer run ecs
