name: Tests

on: [ push ]

jobs:
  phpunit:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        composer-opts:
          - ""
          - --prefer-stable

    steps:
      - uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          ini-values: apc.enable_cli=1
          coverage: xdebug
        env:
          fail-fast: true

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Update dependencies with composer
        run: composer update ${{ matrix.composer-opts }}

      - name: Run tests with PHPUnit
        run: composer run phpunit

      # https://github.com/php-coveralls/php-coveralls#github-actions
      - name: Upload coverage results to Coveralls
        if: ${{ matrix.php-version == '7.4' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
